'use client';
import { create } from 'zustand';
import { persist } from 'zustand/middleware';
export type Language = 'en' | 'fr';
export const translations = {
    en: {
        nav: {
            design: 'Design Yours',
            myOrders: 'My Orders',
            marketplace: 'Marketplace',
            signIn: 'Sign In',
            myAccount: 'My Account',
            startDesigning: 'Start Designing',
        },
        hero: {
            badge: 'Museum-Quality Framing',
            line1: ['Your', 'memories,'],
            line2: ['perfectly', 'framed.'],
            subtitle: 'Upload any photo. Choose your frame. We craft and deliver a',
            subtitleHighlight: 'museum-quality',
            subtitleEnd: 'framed print to your door in days.',
            cta: 'Start Designing',
            ctaBrowse: 'Browse Frames',
            trustRating: '4.9/5',
            trustReviews: 'from 2,400+ customers',
            scroll: 'Scroll',
        },
        stats: {
            sectionLabel: 'By the numbers',
            title: 'Trusted by thousands of',
            titleHighlight: 'art lovers',
            items: [
                { label: 'Frames Crafted', description: 'Orders fulfilled with care across 40+ countries.' },
                { label: 'Average Rating', description: 'Based on 8,400+ verified customer reviews.' },
                { label: 'Average Delivery', description: 'From your upload to your door, worldwide.' },
                { label: 'Archival Quality', description: 'Museum-grade materials guaranteed to last a lifetime.' },
            ],
        },
        howItWorks: {
            sectionLabel: 'The Process',
            title: 'Framing made',
            titleHighlight: 'effortless',
            subtitle: 'Three simple steps between you and a museum-quality piece on your wall.',
            steps: [
                {
                    title: 'Upload Your Photo',
                    description: 'Start with any image — a cherished memory, a fine art print, or your favorite snapshot. We support all major formats in full resolution.',
                },
                {
                    title: 'Choose Your Frame',
                    description: 'Browse our curated collection of premium frames — from sleek minimalist wood to ornate gilded designs. Preview in real-time 3D.',
                },
                {
                    title: 'We Craft & Deliver',
                    description: 'Our master craftsmen produce your frame using archival materials. Delivered to your door in 3–5 days, ready to hang.',
                },
            ],
            cta: 'Start your first frame',
        },
        showcase: {
            sectionLabel: 'Our Collection',
            title: 'Find your perfect',
            titleHighlight: 'frame',
            viewAll: 'View all frames →',
            preview: 'Preview',
            badges: {
                bestSeller: 'Best Seller',
                modern: 'Modern',
                premium: 'Premium',
                eco: 'Eco',
                luxury: 'Luxury',
                new: 'New',
            },
        },
        testimonials: {
            sectionLabel: 'Testimonials',
            title: 'What our customers',
            titleHighlight: 'love',
            items: [
                {
                    name: 'Sophie Marceau',
                    role: 'Interior Designer, Paris',
                    text: "I've ordered from FrameItUp three times now. Every single time the quality exceeded my expectations. The oak frame I chose for my living room gets compliments from every guest.",
                    frame: 'Oslo Classic',
                },
                {
                    name: 'Marcus Chen',
                    role: 'Photographer, New York',
                    text: "As a professional photographer, I'm extremely picky about print quality. FrameItUp uses museum-grade archival paper and the color accuracy is stunning. These are the frames I use for my gallery shows.",
                    frame: 'Noir Élégant',
                },
                {
                    name: 'Emma Johansson',
                    role: 'Art Collector, Stockholm',
                    text: "The Galerie Gold frame is absolutely breathtaking. It transformed my artwork into something that belongs in a museum. Delivery was incredibly fast — I ordered on Monday and it arrived Wednesday!",
                    frame: 'Galerie Gold',
                },
                {
                    name: 'Luca Rossi',
                    role: 'Architect, Milan',
                    text: "The Terra Antica frame perfectly complements my apartment's design aesthetic. The craftsmanship is impeccable — you can feel the quality. FrameItUp is the only place I'll ever order frames from.",
                    frame: 'Terra Antica',
                },
            ],
        },
        cta: {
            badge: 'Free shipping on first order',
            title: 'Your wall deserves',
            titleShimmer: 'something',
            titleGradient: 'extraordinary.',
            subtitle: 'Join over 50,000 customers who have transformed their spaces with FrameItUp. Premium quality, crafted with love, delivered to your door.',
            startDesigning: 'Start Designing Now',
            browseCollection: 'Browse Collection',
            guarantees: [
                { icon: '🎨', label: 'Archival quality' },
                { icon: '🚀', label: '3-day delivery' },
                { icon: '♻️', label: 'Eco materials' },
                { icon: '💯', label: '30-day guarantee' },
            ],
        },
        footer: {
            tagline: 'Museum-quality custom frames, crafted with care and delivered to your door. Transform your memories into timeless art.',
            product: 'Product',
            company: 'Company',
            support: 'Support',
            links: {
                browseFrames: 'Browse Frames',
                designYours: 'Design Yours',
                myOrders: 'My Orders',
                marketplace: 'Marketplace',
                aboutUs: 'About Us',
                craftsmanship: 'Craftsmanship',
                sustainability: 'Sustainability',
                blog: 'Blog',
                faq: 'FAQ',
                shipping: 'Shipping & Returns',
                contact: 'Contact Us',
                privacy: 'Privacy Policy',
            },
            newsletter: {
                title: 'Get framing inspiration',
                subtitle: 'New collections, design tips and exclusive offers.',
                placeholder: 'your@email.com',
                subscribe: 'Subscribe',
            },
            copyright: '© 2026 FrameItUp. All rights reserved.',
            paymentsBy: 'Payments secured by',
        },
        authPage: {
            signInTitle: 'Welcome back',
            signInSubtitle: 'Sign in to manage your custom frame orders',
            signUpTitle: 'Create your account',
            signUpSubtitle: 'Start ordering premium custom frames for your artwork',
        },
        framesPage: {
            sectionLabel: 'Artisan Collections',
            title: 'Exquisite Handcrafted Frame Profiles',
            subtitle: 'Select from our premium curation of materials, hand-finished colorways, and sizes to elevate your artwork or photography.',
            perLinearMeter: 'per linear meter',
            width: 'Width',
            height: 'Height',
            depth: 'Depth',
            designWith: 'Design With This Frame',
            profile: 'Profile',
        },
        configurePage: {
            title: 'Configure Artwork',
            uploadTitle: 'Upload Your Custom Design',
            uploadDesc: 'Drag & drop your artwork or high-resolution picture. We support PNG, JPEG, and WebP formats.',
            chooseFile: 'Choose file',
            analyzing: 'Analyzing layout & detail...',
            preview2d: '2D Detailed View',
            preview3d: 'Realistic 3D Preview',
            resolutionHD: 'Ultra HD Resolution',
            resolutionStandard: 'Standard Resolution',
            totalDimensions: 'Total Frame Outer Dimensions',
            suggestionsTitle: 'Smart Color Palette suggestions',
            suggestionsDesc: 'Extracted matching shades from your design',
            delete: 'Delete',
            steps: {
                size: 'Size',
                frame: 'Frame',
                matting: 'Matting',
                glass: 'Glass',
            },
            presetDimensions: 'Preset standard dimensions',
            customInputs: 'Custom size inputs (in mm)',
            width: 'Width (mm)',
            height: 'Height (mm)',
            selectProfile: 'Select frame profile material',
            addPassePartout: 'Add passe-partout matting',
            passePartoutDesc: 'Adds classic borders and dimensions',
            matWidth: 'Mat Width',
            matColor: 'Mat Board Color',
            selectGlazing: 'Select glazing type (protective glass)',
            glazingTypes: {
                standard: 'Standard Acrylic',
                uv: 'UV Protective',
                antiReflective: 'Anti-Reflective',
                museum: 'Museum Quality',
                standardDesc: 'Shatter-resistant, lightweight, basic safety',
                uvDesc: 'Blocks 99% UV radiation, prevents fading',
                antiReflectiveDesc: 'Matte reflection reduction for high glare rooms',
                museumDesc: 'Ultra-clear, maximum UV blocking & reflection reduction',
            },
            frameProfile: 'Frame Profile',
            qty: 'Qty:',
            totalPrice: 'Total price',
            checkoutBtn: 'Proceed to Checkout',
        },
        ordersPage: {
            dashboard: 'Dashboard',
            title: 'My Orders & Tracking',
            subtitle: 'Trace the handcrafting progress and shipping status of your custom frame collections.',
            emptyTitle: 'No Orders Placed Yet',
            emptyDesc: 'Design a gorgeous custom frame for your artwork to begin tracking its progress.',
            startDesigning: 'Start Designing',
            orderPlaced: 'Order Placed',
            totalCost: 'Total Cost',
            shipTo: 'Ship to',
            trackingRef: 'Tracking Ref',
            steps: {
                pending: 'Order Registered',
                payment: 'Payment Confirmed',
                production: 'In Production',
                quality: 'Quality Check',
                shipped: 'Shipped',
                delivered: 'Delivered',
            },
            customFrame: 'Custom {name} Frame',
            glass: 'Glass',
            qty: 'Qty',
        },
        accountPage: {
            badge: 'My Profile',
            title: 'Account Settings',
            subtitle: 'Manage your personal information, security, and connected accounts.',
        },
        checkoutPage: {
            title: 'Shipping & Customer Info',
            firstName: 'First Name',
            lastName: 'Last Name',
            email: 'Email',
            whatsapp: 'Whatsapp',
            addressLine1: 'Address Line 1',
            addressLine2: 'Address Line 2 (Optional)',
            city: 'City',
            state: 'State / Province',
            postalCode: 'Postal Code',
            country: 'Country',
            paymentMethod: 'Select Payment Method',
            momo: 'Mobile Money (MTN / Orange)',
            momoNum: 'Mobile Money Phone Number',
            cod: 'Cash on Delivery (COD)',
            phonePlaceholder: 'e.g. 6xxxxxxxx',
            errors: {
                required: 'Required',
                invalidEmail: 'Invalid email',
                invalidMomo: 'Invalid phone number (9 digits required)',
            },
            summary: 'Order Summary',
            items: 'Items',
            subtotal: 'Subtotal',
            shipping: 'Shipping',
            shippingFree: 'Free',
            total: 'Total',
            placeOrder: 'Place Order',
            placing: 'Placing order...',
            cinetpay: {
                title: 'Mobile Money Secure Gateway',
                init: 'Select your mobile operator to start the transaction.',
                momoWallet: 'Mobile Wallet payment push.',
                ussdPush: 'Sending USSD Push notification to your phone...',
                ussdConfirm: 'Please check your phone screen for the prompt and enter your PIN.',
                pinEnter: 'Enter your simulated CinetPay validation code / PIN to authorize payment:',
                payBtn: 'Authorize Payment',
                cancelBtn: 'Cancel & Return',
                success: 'Payment verified successfully!',
            }
        },
        successPage: {
            badge: 'Order Confirmed',
            title: 'Thank You for Your Order!',
            desc: 'Your premium custom frame is officially in queue. Our artisans are reviewing your resolution specs to begin handcrafting.',
            orderId: 'Order ID',
            tracking: 'Tracking Number',
            paymentMode: 'Payment Mode',
            totalAmount: 'Total Amount',
            estimatedDelivery: 'Estimated Delivery',
            codWarning: 'Please prepare the cash payment of {total} to hand over to the delivery agent.',
            onlineSuccess: 'Transaction successfully settled online via MTN/Orange wallet.',
            invoiceSent: 'We sent a secure order validation invoice to your registered email address.',
            statusTrack: 'You can follow the live status of your frame’s construction on your dashboard.',
            trackBtn: 'Track in My Orders',
            designAnother: 'Design Another Frame',
            calculating: 'Calculating...',
        },
    },
    fr: {
        nav: {
            design: 'Créer le vôtre',
            myOrders: 'Mes commandes',
            marketplace: 'Marketplace',
            signIn: 'Se connecter',
            myAccount: 'Mon compte',
            startDesigning: 'Commencer',
        },
        hero: {
            badge: 'Encadrement qualité muséale',
            line1: ['Vos', 'souvenirs,'],
            line2: ['parfaitement', 'encadrés.'],
            subtitle: 'Importez votre photo. Choisissez votre cadre. Nous fabriquons et livrons un',
            subtitleHighlight: 'encadrement qualité muséale',
            subtitleEnd: 'à votre porte en quelques jours.',
            cta: 'Commencer',
            ctaBrowse: 'Voir les cadres',
            trustRating: '4,5/5',
            trustReviews: 'avis de plus de 50 clients',
            scroll: 'Défiler',
        },
        stats: {
            sectionLabel: 'En chiffres',
            title: 'La confiance de milliers',
            titleHighlight: "d'amoureux de l'art",
            items: [
                { label: 'Cadres fabriqués', description: 'Commandes traitées avec soin' },
                { label: 'Note moyenne', description: 'Basé sur plus de 50 avis clients vérifiés.' },
                { label: 'Livraison moyenne', description: 'De votre téléchargement à votre porte.' },
                { label: 'Qualité archivale', description: 'Matériaux de qualité muséale garantis pour durer toute une vie.' },
            ],
        },
        howItWorks: {
            sectionLabel: 'Le processus',
            title: "L'encadrement rendu",
            titleHighlight: 'simple',
            subtitle: 'Trois étapes simples entre vous et une pièce de qualité muséale sur votre mur.',
            steps: [
                {
                    title: 'Importez votre photo',
                    description: 'Commencez avec n\'importe quelle image — un souvenir précieux, une reproduction fine ou votre photo préférée. Nous supportons tous les formats majeurs en pleine résolution.',
                },
                {
                    title: 'Choisissez votre cadre',
                    description: 'Parcourez notre collection de cadres premium — du bois minimaliste aux designs dorés ornés. Aperçu en 3D en temps réel.',
                },
                {
                    title: 'Nous fabriquons & livrons',
                    description: 'Nos artisans maîtres produisent votre cadre avec des matériaux d\'archivage. Livré à votre porte en 3 à 5 jours, prêt à accrocher.',
                },
            ],
            cta: 'Commencez votre premier cadre',
        },
        showcase: {
            sectionLabel: 'Notre collection',
            title: 'Trouvez votre',
            titleHighlight: 'cadre parfait',
            viewAll: 'Voir tous les cadres →',
            preview: 'Aperçu',
            badges: {
                bestSeller: 'Best-seller',
                modern: 'Moderne',
                premium: 'Premium',
                eco: 'Éco',
                luxury: 'Luxe',
                new: 'Nouveau',
            },
        },
        testimonials: {
            sectionLabel: 'Témoignages',
            title: 'Ce que nos clients',
            titleHighlight: 'adorent',
            items: [
                {
                    name: 'Sophie',
                    role: 'Décoratrice d\'intérieur, Douala',
                    text: "J'ai commandé chez FrameItUp trois fois maintenant. Chaque fois, la qualité a dépassé mes attentes. Le cadre que j'ai choisi pour mon salon reçoit des compliments de chaque invité.",
                    frame: 'Classic',
                },
                {
                    name: 'Larissa nono',
                    role: 'Entrepreneur, Yaoundé',
                    text: "En tant que  professionnel, je suis très exigeant sur la qualité d'impression. FrameItUp utilise du papier archivistique de qualité muséale et la précision des couleurs est stupéfiante. Le cadre est magnifique et a transformé mon bureau.",
                    frame: 'Noir Élégant',
                },
                {
                    name: 'Merveille Yolande',
                    role: 'Medecin, Yaoundé',
                    text: "Le cadre est absolument époustouflant. Il a transformé ma photo en quelque chose d'exceptionnel. La livraison était incroyablement rapide — j'ai commandé lundi et c'est arrivé très vite!",
                    frame: 'Galerie Gold',
                },
            ],
        },
        cta: {
            badge: 'Livraison offerte pour la 1ère commande',
            title: 'Votre mur mérite',
            titleShimmer: 'quelque chose',
            titleGradient: "d'extraordinaire.",
            subtitle: "Rejoignez plus de 50 clients qui ont transformé leurs espaces avec FrameItUp. Qualité premium, fabriqué avec passion, livré à votre porte.",
            startDesigning: 'Commencer maintenant',
            browseCollection: 'Voir la collection',
            guarantees: [
                { icon: '🎨', label: 'Qualité archivale' },
                { icon: '🚀', label: 'Livraison en 5 jours' },
                { icon: '♻️', label: 'Matériaux éco' },
                { icon: '💯', label: 'Garantie 30 jours' },
            ],
        },
        footer: {
            tagline: 'Des cadres personnalisés de qualité muséale, fabriqués avec soin et livrés à votre porte. Transformez vos souvenirs en art intemporel.',
            product: 'Produit',
            company: 'Entreprise',
            support: 'Assistance',
            links: {
                browseFrames: 'Parcourir les cadres',
                designYours: 'Créer le vôtre',
                myOrders: 'Mes commandes',
                marketplace: 'Marketplace',
                aboutUs: 'À propos',
                craftsmanship: 'Savoir-faire',
                sustainability: 'Durabilité',
                blog: 'Blog',
                faq: 'FAQ',
                shipping: 'Livraison & Retours',
                contact: 'Nous contacter',
                privacy: 'Politique de confidentialité',
            },
            newsletter: {
                title: 'Inspirations encadrement',
                subtitle: 'Nouvelles collections, conseils design et offres exclusives.',
                placeholder: 'votre@email.com',
                subscribe: "S'abonner",
            },
            copyright: '© 2026 FrameItUp. Tous droits réservés.',
            paymentsBy: 'Paiements sécurisés par',
        },
        authPage: {
            signInTitle: 'Bon retour',
            signInSubtitle: 'Connectez-vous pour gérer vos commandes de cadres personnalisés',
            signUpTitle: 'Créer votre compte',
            signUpSubtitle: 'Commencez à commander des cadres personnalisés premium pour votre art',
        },
        framesPage: {
            sectionLabel: 'Collections artisanales',
            title: 'Profils de cadres artisanaux exquis',
            subtitle: 'Choisissez parmi notre sélection premium de matériaux, coloris finis à la main, et tailles pour sublimer votre art ou photographie.',
            perLinearMeter: 'par mètre linéaire',
            width: 'Largeur',
            height: 'Hauteur',
            depth: 'Profondeur',
            designWith: 'Créer avec ce cadre',
            profile: 'Profil',
        },
        configurePage: {
            title: 'Configurer l\'œuvre',
            uploadTitle: 'Importez votre création personnalisée',
            uploadDesc: 'Glissez-déposez votre œuvre ou une image haute résolution. Formats acceptés : PNG, JPEG et WebP.',
            chooseFile: 'Choisir un fichier',
            analyzing: 'Analyse du format et des détails...',
            preview2d: 'Vue détaillée 2D',
            preview3d: 'Aperçu 3D réaliste',
            resolutionHD: 'Résolution Ultra HD',
            resolutionStandard: 'Résolution Standard',
            totalDimensions: 'Dimensions extérieures totales du cadre',
            suggestionsTitle: 'Suggestions de passe-partout',
            suggestionsDesc: 'Teintes extraites de votre image pour s\'accorder au mieux',
            delete: 'Supprimer',
            steps: {
                size: 'Taille',
                frame: 'Cadre',
                matting: 'Passe-partout',
                glass: 'Verre',
            },
            presetDimensions: 'Dimensions standard prédéfinies',
            customInputs: 'Dimensions personnalisées (en mm)',
            width: 'Largeur (mm)',
            height: 'Hauteur (mm)',
            selectProfile: 'Sélectionnez le matériau du cadre',
            addPassePartout: 'Ajouter un passe-partout',
            passePartoutDesc: 'Ajoute des bordures classiques et du relief',
            matWidth: 'Largeur du passe-partout',
            matColor: 'Couleur du passe-partout',
            selectGlazing: 'Sélectionnez le type de verre protecteur',
            glazingTypes: {
                standard: 'Acrylique Standard',
                uv: 'Protection UV',
                antiReflective: 'Anti-reflet',
                museum: 'Qualité Muséale',
                standardDesc: 'Résistant aux chocs, léger, sécurité de base',
                uvDesc: 'Bloque 99% des UV, empêche la décoloration',
                antiReflectiveDesc: 'Réduction de la réflexion mate pour pièces lumineuses',
                museumDesc: 'Ultra-transparent, blocage UV et réduction de reflet maximum',
            },
            frameProfile: 'Profil de cadre',
            qty: 'Qté :',
            totalPrice: 'Prix total',
            checkoutBtn: 'Passer à la commande',
        },
        ordersPage: {
            dashboard: 'Tableau de bord',
            title: 'Mes commandes & Suivi',
            subtitle: 'Suivez la fabrication artisanale et l\'état de livraison de vos cadres personnalisés.',
            emptyTitle: 'Aucune commande pour le moment',
            emptyDesc: 'Créez un magnifique cadre personnalisé pour votre œuvre afin de commencer à suivre sa progression.',
            startDesigning: 'Commencer',
            orderPlaced: 'Commande passée',
            totalCost: 'Coût total',
            shipTo: 'Livrer à',
            trackingRef: 'Réf de suivi',
            steps: {
                pending: 'Commande enregistrée',
                payment: 'Paiement confirmé',
                production: 'En production',
                quality: 'Contrôle qualité',
                shipped: 'Expédié',
                delivered: 'Livré',
            },
            customFrame: 'Cadre personnalisé {name}',
            glass: 'Verre',
            qty: 'Qté',
        },
        accountPage: {
            badge: 'Mon Profil',
            title: 'Paramètres du compte',
            subtitle: 'Gerez vos informations personnelles, votre sécurité et vos comptes connectés.',
        },
        checkoutPage: {
            title: 'Informations de livraison & Client',
            firstName: 'Prénom',
            lastName: 'Nom',
            email: 'E-mail',
            whatsapp: 'Whatsapp',
            addressLine1: 'Adresse ligne 1',
            addressLine2: 'Adresse ligne 2 (Facultatif)',
            city: 'Ville',
            state: 'Région / Province',
            postalCode: 'Code postal',
            country: 'Pays',
            paymentMethod: 'Sélectionnez le mode de paiement',
            momo: 'Mobile Money (MTN / Orange)',
            momoNum: 'Numéro Mobile Money',
            cod: 'Paiement à la livraison (COD)',
            phonePlaceholder: 'ex. 6xxxxxxxx',
            errors: {
                required: 'Requis',
                invalidEmail: 'E-mail invalide',
                invalidMomo: 'Numéro de téléphone invalide (9 chiffres requis)',
            },
            summary: 'Récapitulatif de la commande',
            items: 'Articles',
            subtotal: 'Sous-total',
            shipping: 'Livraison',
            shippingFree: 'Gratuit',
            total: 'Total',
            placeOrder: 'Passer la commande',
            placing: 'Traitement de la commande...',
            cinetpay: {
                title: 'Passerelle sécurisée Mobile Money',
                init: 'Sélectionnez votre opérateur mobile pour commencer la transaction.',
                momoWallet: 'Paiement push sur portefeuille mobile.',
                ussdPush: 'Envoi d\'une notification USSD Push sur votre téléphone...',
                ussdConfirm: 'Veuillez vérifier l\'écran de votre téléphone et saisir votre code PIN.',
                pinEnter: 'Entrez votre code de validation / PIN CinetPay simulé pour autoriser le paiement :',
                payBtn: 'Autoriser le paiement',
                cancelBtn: 'Annuler & Retourner',
                success: 'Paiement vérifié avec succès !',
            }
        },
        successPage: {
            badge: 'Commande confirmée',
            title: 'Merci pour votre commande !',
            desc: 'Votre cadre personnalisé premium est officiellement en cours de traitement. Nos artisans examinent les spécifications de votre image pour commencer la fabrication.',
            orderId: 'ID Commande',
            tracking: 'Numéro de suivi',
            paymentMode: 'Mode de paiement',
            totalAmount: 'Montant total',
            estimatedDelivery: 'Livraison estimée',
            codWarning: 'Veuillez préparer le paiement en espèces de {total} à remettre à l\'agent de livraison.',
            onlineSuccess: 'Transaction réglée en ligne avec succès via MTN/Orange Money.',
            invoiceSent: 'Nous avons envoyé une facture sécurisée à l\'adresse e-mail enregistrée.',
            statusTrack: 'Vous pouvez suivre l\'état de fabrication de votre cadre en temps réel sur votre tableau de bord.',
            trackBtn: 'Suivre mes commandes',
            designAnother: 'Créer un autre cadre',
            calculating: 'Calcul...',
        },
    },
} as const;
export type Translations = typeof translations.en;
interface LanguageState {
    language: Language;
    t: Translations;
    setLanguage: (lang: Language) => void;
}
export const useLanguageStore = create<LanguageState>()(
    persist(
        (set) => ({
            language: 'fr',
            t: translations.fr as any,
            setLanguage: (lang: Language) =>
                set({ language: lang, t: translations[lang] as any }),
        }),
        {
            name: 'frameitup-language',
        }
    )
);
